gtnh.settings.blowdryerTag = 0.2.2

modName = MekanismTweaks
modId = mekanismtweaks
modGroup = dev.felnull.mekanismtweaks
useModGroupForPublishing = true
autoUpdateBuildScript = false

minecraftVersion = 1.7.10
forgeVersion = 10.13.4.1614
channel = stable
mappingsVersion = 12
remoteMappings = https\://raw.githubusercontent.com/MinecraftForge/FML/1.7.10/conf/
developmentEnvironmentUserName = Developer

enableModernJavaSyntax = false
enableGenericInjection = true

generateGradleTokenClass =
gradleTokenVersion = VERSION

usesMixins = true
mixinsPackage = mixin
mixinPlugin =

usesShadowedDependencies = false
includeWellKnownRepositories = true
usesMavenPublishing = false
disableSpotless = true
disableCheckstyle = true

org.gradle.configuration-cache = false
org.gradle.parallel = true
