org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=false
org.gradle.caching=false

# Minecraft and NeoForge
minecraft_version=1.19.1
forge_version=42.0.9

# Mekanism (compile and development runtime)
mekanism_version=1.19.1-10.3.1.468

# The mod
mod_id=mekanismtweaks
mod_name=MekanismTweaks
mod_group=dev.felnull.mekanismtweaks
mod_version=1.19.1-1.1
mod_author=nin8995
mod_description=Higher Consumption, Higher Performance
