modLoader = "javafml"
loaderVersion = "[2,)"
license = "Unlicense"

[[mods]]
modId = "mekanismtweaks"
version = "${file.jarVersion}"
displayName = "MekanismTweaks"
authors = "nin8995"
description = '''
Higher Consumption, Higher Performance.
Raises the maximum number of Speed, Energy and Chemical Upgrades, keeps the effect per 8 upgrades,
and lets the effect of surplus Energy Upgrades decay against the Speed Upgrades.
'''

[[mixins]]
config = "mekanismtweaks.mixins.json"

[[dependencies.mekanismtweaks]]
modId = "neoforge"
type = "required"
versionRange = "[20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mekanismtweaks]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.4]"
ordering = "NONE"
side = "BOTH"

[[dependencies.mekanismtweaks]]
modId = "mekanism"
type = "required"
versionRange = "[10.5,10.6)"
ordering = "AFTER"
side = "BOTH"
