modLoader = "javafml"
loaderVersion = "[47,)"
license = "Unlicense"

[[mods]]
modId = "mekanismtweaks"
version = "${file.jarVersion}"
displayName = "MekanismTweaks"
authors = "nin8995"
description = '''
Higher Consumption, Higher Performance.
Raises the maximum number of Speed, Energy and Gas Upgrades, keeps the effect per 8 upgrades,
and lets the effect of surplus Energy Upgrades decay against the Speed Upgrades.
'''

[[dependencies.mekanismtweaks]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mekanismtweaks]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.mekanismtweaks]]
modId = "mekanism"
mandatory = true
versionRange = "[10.4,10.5)"
ordering = "AFTER"
side = "BOTH"
